# "Thanks for downloading TeaModeration, if you need help, all is explain in the wiki.".

# Database informations (for MySQL database).
database:
  host: "localhost"
  user: "anotherworlduser"
  password: ")i08MyYR3ZI8whll"
  dbName: "anotherworld"
  port: 3306

lang: "en_US"