# "Thanks for downloading TeaModeration, if you need help, all is explain in the wiki.".

# Database informations (for MySQL database).
database:
  host: "localhost"
  user: "anotherworlduser"
  password: ")i08MyYR3ZI8whll"
  dbName: "anotherworld"
  port: 3306

#Time
time:
  year: "year"
  years: "years"
  month: "month"
  months: "months"
  week: "week"
  weeks: "weeks"
  day: "day"
  days: "days"
  hour: "hour"
  hours: "hours"
  minute: "minute"
  minutes: "minutes"
  second: "second"
  seconds: "seconds"
  permanently: "permanently"


#Errors
errors:
  basic: "You can't use this command, Please follow this Schema :"


mute:
  by: "You have been muted by {0}"
  reason: "Reason : {0}"
  time: "for {0}" #Example: for 6 days

ban:
  by: "You have been banned by {0}"
  time-1: "Your ban will be removed on {0} at {1}"
  time-2: "for {0}" #Example: for 6 days

kick:
  by: "You have been banned by {0}"

banlist:
  banned: "was banned"
  by: "By :"
  reason: "Reason :"
  time: "How much time :"
  when: "When :"
  expiration: "Expiration :"